
{{- $distro := .distro -}}
{{- $suite := .suite -}}

{{- $architecture := .architecture -}}

architecture: {{ $architecture }}

actions:
  - action: apt
    description: Install base packages
    packages:
      - init
      - initramfs-tools
      - sudo

  - action: apt
    description: Install firmwares
    packages:
{{ if eq $distro "debian" }}
      - firmware-brcm80211
      - firmware-iwlwifi
      - firmware-linux
      - firmware-realtek
{{ else if eq $distro "ubuntu" }}
      - linux-firmware
{{ end }}
  
  - action: apt
    description: Install system utilities
    packages:
      - apt-listchanges
      - apt-utils
      - bash-completion
      - bc
      - binutils
      - cloud-initramfs-growroot
      - curl
      - eject
      - exfat-fuse
      - file
      - gpg
      - haveged
      - htop
      - lbzip2
      - less
      - locales
      - man-db
      - nano
      - ntfs-3g
      - python3
      - python3-pip
      - software-properties-common
      - ssh
      - sysfsutils
      - tmux
      - u-boot-tools
      - vim
      - wget
      - whiptail
      - xz-utils
      - zram-tools
{{ if ne $suite "buster"}}
      - python-is-python3
      - systemd-timesyncd
{{ end }}
{{ if eq $suite "bookworm" }}
      - efibootmgr
      - systemd-boot
{{ end }}

  - action: apt
    description: Install network utilities
    packages:
      - avahi-daemon
      - bluetooth
      - ca-certificates
      - dnsmasq
      - ldnsutils
      - ifupdown
      - iproute2
      - iptables
      - iputils-ping
      - iw
      - network-manager
      - samba
      - wireless-regdb
      - wpasupplicant

  - action: apt
    description: Install audio utilities
    packages:
      - alsa-utils
{{ if eq $suite "bookworm" }}
      - pipewire-audio
{{ else }}
      - pulseaudio
      - pulseaudio-module-bluetooth
{{ end }}
{{ if ne $suite "buster"}}
      - alsa-ucm-conf
{{ end }}

  - action: apt
    description: Install hardware utilities
    packages:
      - gpiod
      - hdparm
      - i2c-tools
      - mtd-utils
      - pciutils
      - rfkill
      - spi-tools
      - usbutils

{{ if eq $suite "bullseye"}}
  - action: run
    description: Installl wpasupplicant from backports
    chroot: true
    command: |
      set -e
      apt-get install -y -t {{ $suite }}-backports \
        wpasupplicant
{{ end }}

  - action: apt
    description: Install Radxa backported packages
    packages:
      - u-boot-menu

  - action: apt
    description: Install Radxa packages
    packages:
      - android-tools-adbd
      - libreelec-alsa-utils
      - radxa-bootutils
      - radxa-firmware
      - radxa-otgutils
      - radxa-udev

  # - action: run
  #   description: Install custom packages, rsetup
  #   chroot: true
  #   command: |
  #     dpkg -i --force-overwrite custom_packages/rsetup/rsetup_0.4.12_all.deb
  #     dpkg -i --force-overwrite custom_packages/rsetup/rsetup-config-first-boot_0.4.12_all.deb
  #     apt-get update
  #     apt --fix-broken install -y

  - action: apt
    description: Install S3DP needed packages
    packages:
      - python3-venv=3.9.2-3
      - python3-dev=3.9.2-3
      - device-tree-compiler=1.6.0-1
      - gdisk=1.0.6-1.1
      - jq=1.6-2.1
      - librtui=0.1.6
      - parted=3.4-1
      - python3-yaml=5.3.1-5
      - git=1:2.30.2-1+deb11u4
      #swupdate
      - cmake=3.18.4-2+deb11u1
      - libyaml-dev=0.2.2-1
      - libubi-dev=1:2.1.2-2
      - libmtd-dev=1:2.1.2-2
      - libsystemd-dev=247.3-7+deb11u6
      - libwebsockets-dev=4.0.20-2
      - liburiparser-dev=0.9.4+dfsg-1+deb11u1
      - liblua5.2-dev=5.2.4-1.1+b3
      - libssl-dev=1.1.1w-0+deb11u2
      - libconfig-dev=1.5-0.4
      - libarchive-dev=3.4.3-2+deb11u2
      - libzmq3-dev=4.3.4-1+deb11u1
      - libcurl4-gnutls-dev=7.74.0-1.3+deb11u14
      - libjson-c-dev=0.15-2+deb11u1
      - libzstd-dev=1.4.8+dfsg-2.1
